#!/bin/sh
name="$1"
file="$2"

clang \
    -Wall -Wextra -Werror -pedantic \
    -o 'particle_test' \
    -std=c23 \
    -g \
    particle_test.c \
    particle.c


if ! ./particle_test; then
    exit
fi


clang \
    -Wall -Wextra -Werror -pedantic \
    -o "${name}" \
    -g \
    -std=c23 \
    "${name}.c" \
    particle.c \

"./${name}" "${file}"

rm "${name}"
